language: go
go:
    - 1.4
notifications:
    irc:
        channels:
            - "irc.mozilla.org#datapipeline"
before_install:
    - sudo add-apt-repository ppa:andykimpe/cmake3 -y
    - sudo add-apt-repository ppa:maxmind/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -y protobuf-compiler cmake libgeoip-dev

install:
    - bash bin/build_pipeline_heka.sh

script:
    - cd build/heka
    - . env.sh
    - cd build
    - make
    - go test github.com/mozilla-services/data-pipeline/s3splitfile
